(function(){
'use strict';
const A=window.App,E=A.escape,I=A.icon;
const definitions={
 attack:{name:'攻防演练中心',icon:'activity',items:[['arena','攻防演练场','实时演练与回放','activity'],['tasks','任务管理','方案与执行记录','clock'],['banks','题库管理','题库与导入','file'],['models','模型管理','模型与智能体','box']]},
 review:{name:'内容审核中心',icon:'shield',sections:[{title:'工作台',items:[['records','审核记录','自动审核结果','file'],['samples','治理样本','回归与标注','layers'],['rules','规则治理','验证与版本','settings']]},{title:'系统配置',items:[['models','模型管理','模型连接配置','box']]}]},
 scan:{name:'漏洞扫描中心',icon:'code',items:[['tasks','扫描任务','创建与进度','activity'],['findings','漏洞处置','证据与复测','alert'],['assets','资产管理','扫描目标','layers'],['reports','扫描报告','结果与修复建议','file']]}
};
A.centers={
 accountToggle(){const menu=document.getElementById('center-user-menu'),button=document.getElementById('center-user-button');const open=menu.hidden;menu.hidden=!open;button.setAttribute('aria-expanded',String(open));},
 toggle(){A.data.ui ||= {};A.data.ui.sidebarCollapsed=!A.data.ui.sidebarCollapsed;A.save();A.centers.render();document.getElementById('center-toggle')?.focus();},
 current(){if(A.page==='attack')return A.attack.selected?'tasks':A.attack.tab;if(A.page==='review')return A.review.tab;if(A.page==='scan')return A.data.scan.tab==='overview'?'tasks':A.data.scan.tab||'tasks';return '';},
 count(id){if(A.page==='attack'&&id==='results')return A.attack.db.tasks.filter(t=>A.attack.metrics(t).done>0).length;if(A.page==='review'&&id==='inbox')return A.data.review.events.filter(e=>e.status==='pending').length;if(A.page==='scan'&&id==='findings')return A.data.scan.projects.reduce((n,p)=>n+p.findings.filter(f=>!['fixed','ignored'].includes(f.state)).length,0);return null;},
 go(id){A.closeModal();A.closeDrawer();if(A.page==='attack')A.attack.setTab(id);if(A.page==='review')A.review.setTab(id);if(A.page==='scan'){A.data.scan.tab=id;A.render();}window.scrollTo({top:0,behavior:'instant'});},
 render(){const def=definitions[A.page],host=document.getElementById('center-sidebar'),app=document.getElementById('app');app.classList.toggle('has-center-nav',!!def);app.classList.toggle('nav-collapsed',!!A.data.ui?.sidebarCollapsed);document.querySelector(def?'.top-actions':'.standalone-left').appendChild(document.getElementById('workspace-return'));if(!def){host.innerHTML='';return;}const current=A.centers.current(),item=(def.sections||[{items:def.items}]).flatMap(s=>s.items).find(n=>n[0]===current);host.innerHTML=`<div class="center-brand"><span class="center-mobile-mark">${I(def.icon,22)}</span><strong>${def.name}</strong><button id="center-toggle" class="center-toggle" onclick="App.centers.toggle()" aria-controls="center-navigation" aria-expanded="${!A.data.ui?.sidebarCollapsed}" aria-label="${A.data.ui?.sidebarCollapsed?'展开侧边栏':'收起侧边栏'}" title="${A.data.ui?.sidebarCollapsed?'展开侧边栏':'收起侧边栏'}"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7"><rect x="3" y="4" width="18" height="16" rx="3"/><path d="M9 4v16"/></svg></button></div><nav id="center-navigation" aria-label="${def.name}">${A.page==='attack'?`<button class="center-create ${current==='create'?'active':''}" onclick="App.attack.newTask()" aria-label="新建攻防任务" title="新建攻防任务">${I('plus',19)}<span>新建攻防任务</span></button>`:''}${(def.sections||[{title:'工作台',items:def.items}]).map(sec=>`<div class="center-section">${E(sec.title)}</div>${sec.items.map(([id,name,desc,icon])=>{const count=A.centers.count(id);return `<button class="center-nav-item ${current===id?'active':''}" onclick="App.centers.go('${id}')" aria-label="${name}" title="${name} · ${desc}" ${current===id?'aria-current="page"':''}><span class="center-nav-icon">${I(icon,17)}</span><span class="center-nav-text"><strong>${name}</strong><small>${desc}</small></span>${count?`<span class="center-nav-count">${count}</span>`:''}</button>`;}).join('')}`).join('')}</nav><div class="center-sidebar-bottom"><button id="center-user-button" onclick="App.centers.accountToggle()" class="center-account" aria-label="安全管理员" aria-expanded="false"><span class="avatar">安</span><span class="center-account-text"><strong>安全管理员</strong></span><span class="account-chevron">›</span></button><div id="center-user-menu" class="center-user-menu" hidden><button onclick="App.navigate('workspace')">${I('grid',14)}<span>回到首页</span></button></div></div>`;document.getElementById('current-crumb').innerHTML=`<span>${def.name}</span><span class="center-crumb-slash">/</span><strong>${E(item?.[1]||(current==='create'?'新建攻防任务':'工作台'))}</strong>`;document.title=`${item?.[1]||(current==='create'?'新建攻防任务':def.name)} · ${def.name}`;app.dataset.section=current;}
};
document.addEventListener('click',e=>{if(e.target.closest?.('.center-sidebar-bottom'))return;const m=document.getElementById('center-user-menu');if(m)m.hidden=true;document.getElementById('center-user-button')?.setAttribute('aria-expanded','false');});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){const m=document.getElementById('center-user-menu');if(m)m.hidden=true;document.getElementById('center-user-button')?.setAttribute('aria-expanded','false');}});
const render=A.render;
A.render=function(){render();if(A.session)A.centers.render();};
})();
