/* Event-driven exercise UI. All execution in this standalone demo is simulated. */
(function(){
'use strict';
const A=window.App,X=A.attack,C=A.connections,B=A.banks,E=A.escape,I=A.icon,M=X.methodDependencies;
const phaseNames=['红队生成攻击','蓝队响应','评价模型判定'];
const copy=v=>JSON.parse(JSON.stringify(v));
const defense=t=>t.defense||{mode:'existing',prompt:''};
const resultName=u=>({breach:'已攻破',defended:'已守住',error:'执行异常',pending:'进行中'}[u?.result]||'等待开始');
const safeId=()=>Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7);
X.tab='arena';
X.arena={taskId:null,unitId:null,replay:null};
X.exerciseTask=()=>X.db.tasks.find(t=>t.id===X.arena.taskId)||X.db.tasks[0];
X.canPrompt=m=>m.accessType!=='weights'&&m.kind!=='agent'&&m.protocol==='openai';
X.methodFit=(m,w)=>!!m?.id&&m.accessType!=='weights'&&w.methods.every(n=>X.scenarios.some(s=>s.methods.includes(n)));
X.eligibleTargets=w=>C.eligible('target').filter(m=>X.methodFit(m,w));
X.unitContent=function(t,u){const q=t.bankSnapshot?.items.find(q=>q.id===u.questionId);const fallback=X.sampleContent(u,t);return {prompt:u.attackPrompt||q?.prompt||fallback.prompt,response:u.response||fallback.response,verdict:u.verdict||fallback.verdict};};
X.showArena=function(id){X.arena={taskId:id,unitId:null,replay:null};X.selected=null;X.tab='arena';A.render();};
X.chooseArenaUnit=function(id){X.arena.unitId=id||null;X.arena.replay=null;A.render();};
X.arenaControl=function(action){const t=X.exerciseTask();if(!t)return;if(action==='toggle'){if(!['running','paused'].includes(t.status))return;t.status=t.status==='running'?'paused':'running';}else if(action==='stop'){A.modal('终止攻防任务',`<p>终止 ${E(t.name)}，保留已完成记录</p>`,`<button class="btn" onclick="App.closeModal()">取消</button><button class="btn danger" onclick="App.attack.arenaStop('${t.id}')">终止任务</button>`);return;}A.save();A.render();};
X.arenaStop=function(id){const t=X.db.tasks.find(t=>t.id===id);if(t&&['running','paused'].includes(t.status))t.status='stopped';A.save();A.closeModal();A.render();};
X.replay=function(action){const t=X.exerciseTask();if(!t)return;const u=t.units.find(u=>u.id===X.arena.unitId)||[...t.units].reverse().find(u=>u.events?.length);if(!u?.events?.length){A.toast('此历史记录没有保存过程事件');return;}X.arena.unitId=u.id;if(action==='start')X.arena.replay={index:0,playing:true};else if(action==='pause'&&X.arena.replay)X.arena.replay.playing=!X.arena.replay.playing;else if(action==='next'){X.arena.replay ||= {index:0,playing:false};X.arena.replay.playing=false;X.arena.replay.index=Math.min(u.events.length-1,X.arena.replay.index+1);}else if(action==='live'){X.arena.unitId=null;X.arena.replay=null;}A.render();};

// Three recorded stages per simulated test unit; completion is committed only at judgment.
X.tick=function(){let changed=false;for(const t of X.db.tasks){if(t.status!=='running')continue;const pending=t.units.filter(u=>u.result==='pending');if(!pending.length){t.status='done';changed=true;continue;}const active=pending.filter(u=>u.events?.length);const batch=active.length?active:pending.slice(0,Math.max(1,Math.min(8,t.engine.concurrency||1)));for(const u of batch){u.events ||= [];const phase=u.events.length;if(phase===0){const q=t.bankSnapshot?.items.find(q=>q.id===u.questionId);const text=q?.prompt||X.sampleContent(u,t).prompt;u.attackPrompt=u.method==='Direct'?text:`[${M[u.method]?.label||u.method} · 模拟攻击输入]\n${text}`;}if(phase===1){const preview={...u};X.finishUnit(preview);u.response=preview.result==='error'?'未取得有效模型响应':preview.result==='breach'?'模拟回答越过安全边界：[受限内容已隐藏]':'模拟回答拒绝受限请求，并给出安全替代建议';}if(phase===2){X.finishUnit(u);u.response=u.result==='error'?'未取得有效模型响应':u.result==='breach'?'模拟回答越过安全边界：[受限内容已隐藏]':'模拟回答拒绝受限请求，并给出安全替代建议';u.verdict=u.result==='error'?'执行异常，不计入有效评价':u.result==='breach'?'评价确认突破安全边界':'评价确认守住安全边界';}u.events.push({phase:Math.min(2,phase),time:new Date().toISOString()});}t.ticks=(t.ticks||0)+1;if(!t.units.some(u=>u.result==='pending'))t.status='done';changed=true;}return changed;};
const contentBefore=X.sampleContent;X.sampleContent=function(u,t=X.task){const c=contentBefore(u,t);return {...c,...(u.attackPrompt?{prompt:u.attackPrompt}:{}),...(u.result!=='pending'&&u.response?{response:u.response}:{}),...(u.verdict?{verdict:u.verdict}:{})};};
setInterval(()=>{const r=X.arena.replay;if(!r?.playing||A.page!=='attack'||X.tab!=='arena'||document.querySelector('.overlay.open'))return;const t=X.exerciseTask(),u=t?.units.find(u=>u.id===X.arena.unitId);if(!u?.events?.length){r.playing=false;return;}if(r.index<u.events.length-1)r.index++;else r.playing=false;A.render();},1500);

X.arenaHTML=function(){const t=X.exerciseTask();if(!t)return `<section class="card arena-empty"><h2>尚无攻防任务</h2><p>从左侧新建攻防任务开始</p></section>`;const m=X.metrics(t),available=t.units.filter(u=>u.result!=='pending'||u.events?.length),u=t.units.find(u=>u.id===X.arena.unitId)||available.find(u=>u.result==='pending')||available.at(-1),events=u?.events||[],replay=X.arena.replay,phase=events.length?(replay?events[replay.index]?.phase:events.at(-1).phase):-1,c=u?X.unitContent(t,u):null,final=u&&u.result!=='pending'&&(!replay||phase===2),live=t.status==='running'&&!replay&&u?.result==='pending',blue=defense(t),families=X.db.tasks.filter(x=>(x.seriesId||x.id)===(t.seriesId||t.id));
const unitOptions=available.slice(-100);if(u&&!unitOptions.includes(u))unitOptions.unshift(u);
return `<div class="arena-context"><div><label for="arena-task">当前任务</label><select id="arena-task" onchange="App.attack.showArena(this.value)">${X.db.tasks.map(x=>`<option value="${E(x.id)}" ${x.id===t.id?'selected':''}>${E(x.name)} · 第 ${x.iteration||1} 轮</option>`).join('')}</select></div><div class="arena-context-actions">${X.status(t)}${A.badge('模拟演练','gray')}${['running','paused'].includes(t.status)?`<button class="btn" onclick="App.attack.arenaControl('toggle')">${t.status==='running'?'暂停任务':'继续任务'}</button><button class="btn" onclick="App.attack.arenaControl('stop')">终止任务</button>`:''}<button class="btn" onclick="App.attack.open('${t.id}')">任务详情</button></div></div>
<section class="arena-stage ${live?'is-running':''}" aria-label="攻防演练动态看板"><div class="arena-stage-head"><div><span class="arena-kicker">攻防实况</span><h2>${E(t.name)}</h2></div><span class="arena-stage-status">${replay?'记录回放':live?'正在演练':t.status==='paused'?'任务已暂停':t.status==='stopped'?'任务已终止':t.status==='done'?'演练已完成':'准备中'}</span></div>
<div class="arena-battle"><article class="arena-team red ${phase===0?'active':''}"><div class="arena-team-label"><span>红队</span><b>攻击方</b></div><h3>${u?E(M[u.method]?.label||u.method):'等待攻击输入'}</h3><p>${u?E(X.scene(u.scene)?.name||u.scene):'按任务配置生成测试输入'}</p><div class="arena-team-model">${E(u&&!M[u.method]?.gen&&!(u.method==='FigStep'&&t.engine.figHelper)?'规则 / 模板生成':t.engine.attacker||'规则 / 模板生成')}</div><span class="arena-node-state">${phase===0?'正在生成攻击输入':phase>0?'攻击输入已发送':u?'历史攻击记录':'等待执行'}</span></article>
<div class="arena-bridge"><span>攻击输入</span><div class="arena-signal ${live?'moving':''}"><i></i><i></i><i></i></div><strong>→</strong><small>${u?E(u.id):'—'}</small></div>
<article class="arena-team blue ${phase===1?'active':''}"><div class="arena-team-label"><span>蓝队</span><b>防御方</b></div><h3>${E(X.targetFor(t).name)}</h3><p>${blue.mode==='prompt'?'增加防御提示词':'基准'}</p><div class="arena-team-model">${E(X.targetFor(t).model)}</div><span class="arena-node-state">${phase===1?'正在处理攻击输入':phase===2?'模型响应已记录':u&&u.result!=='pending'?'历史响应已保存':'等待攻击输入'}</span></article></div>
<div class="arena-downlink ${live&&phase===2?'moving':''}">↓</div><article class="arena-judge ${phase===2?'active':''}"><div><span>评价模型</span><strong>${E(t.engine.roles?.judge?.name||t.engine.judge||'未记录')}</strong></div><b class="${final&&u.result==='breach'?'risk':''}">${final?resultName(u):phase===2?'评价中':'等待判定'}</b></article>
<div class="arena-timeline">${phaseNames.map((n,i)=>`<span class="${phase===i?'current':phase>i?'complete':''}"><i>${i+1}</i>${n}</span>`).join('')}</div></section>
<div class="arena-playbar"><label for="arena-unit">展示记录</label><select id="arena-unit" onchange="App.attack.chooseArenaUnit(this.value)"><option value="">跟随当前 / 最近记录</option>${unitOptions.map(x=>`<option value="${x.id}" ${X.arena.unitId===x.id?'selected':''}>${x.id} · ${x.method} · ${resultName(x)}</option>`).join('')}</select><button class="btn small" ${events.length?'':'disabled'} onclick="App.attack.replay('start')">回放过程</button>${replay?`<button class="btn small" onclick="App.attack.replay('pause')">${replay.playing?'暂停回放':'继续回放'}</button><button class="btn small" onclick="App.attack.replay('next')">下一步</button><button class="link-btn" onclick="App.attack.replay('live')">返回实况</button>`:''}</div>
<div class="arena-metrics">${[['完成进度',`${m.done} / ${m.total}`],['已攻破',m.breach],['已守住',m.defended],['攻破率',m.valid?m.asr+'%':'—'],['执行异常',m.errors]].map(([k,v])=>`<div><span>${k}</span><strong>${v}</strong></div>`).join('')}</div>
<div class="arena-lower"><section class="card"><div class="card-head"><h3>当前记录</h3>${u?A.badge(u.method,'gray'):''}</div><div class="card-body arena-evidence"><label>攻击输入</label><p>${E(c?.prompt||'等待生成')}</p><label>蓝队响应</label><p>${E(!u?'等待响应':replay&&phase<1?'等待响应':u.result==='pending'&&phase===0?'等待响应':c.response)}</p><label>评价结论</label><p>${E(final?c.verdict:'尚未完成评价')}</p></div></section><section class="card"><div class="card-head"><h3>风险场景分布</h3><span>已攻破 / 已完成</span></div><div class="card-body">${t.scenes.map(id=>{const rows=t.units.filter(u=>u.scene===id&&u.result!=='pending'),n=rows.filter(u=>u.result==='breach').length;return `<div class="arena-distribution"><div><span>${E(X.scene(id)?.name||id)}</span><b>${n} / ${rows.length}</b></div><div class="progress-track"><div class="progress-fill" style="width:${rows.length?n/rows.length*100:0}%"></div></div></div>`;}).join('')}<button class="link-btn" onclick="App.attack.open('${t.id}');App.attack.detailTab='samples';App.render()">查看全部攻击记录 →</button></div></section></div>
<section class="card arena-iterations"><div class="card-head"><h3>演练迭代</h3><div class="flex"><button class="btn small" onclick="App.attack.repeatTask('${t.id}',false)">再次运行</button><button class="btn small" onclick="App.attack.repeatTask('${t.id}',true)">调整后再演练</button>${families.length>1?`<button class="btn small" onclick="App.attack.compare('${t.id}')">轮次对比</button>`:''}</div></div><div class="arena-rounds">${families.sort((a,b)=>(a.iteration||1)-(b.iteration||1)).map(x=>`<button class="arena-round ${x.id===t.id?'active':''}" onclick="App.attack.showArena('${x.id}')"><strong>第 ${x.iteration||1} 轮</strong><span>${E(x.changeSummary||'首次演练')}</span><small>${X.metrics(x).valid?X.metrics(x).asr+'%':'—'} 攻破率 · ${X.statusLabel(x)}</small></button>`).join('')}</div></section>`;
};
X.statusLabel=t=>({running:'进行中',paused:'已暂停',done:'已完成',stopped:'已终止'}[t.status]);
X.overview=function(){if(X.tab==='arena')return A.heading('','攻防演练场','')+X.arenaHTML();if(X.tab==='create')return A.heading('','新建攻防任务','')+(X.creationHTML||'');if(X.tab==='banks')return A.heading('','题库管理','')+B.render();if(X.tab==='models')return A.heading('','模型管理','管理模型与智能体连接，为被测对象和演练角色提供模型资产')+X.models();return A.heading('','任务管理','')+X.historyHTML();};
X.historyHTML=function(){return `<section class="card"><div class="toolbar"><select aria-label="任务状态筛选" onchange="App.attack.filter=this.value;App.render()">${[['all','全部状态'],['running','进行中'],['paused','已暂停'],['done','已完成'],['stopped','已终止']].map(([v,l])=>`<option value="${v}" ${X.filter===v?'selected':''}>${l}</option>`).join('')}</select><input class="input" aria-label="搜索任务管理" placeholder="搜索任务、模型或编号" value="${E(X.query)}" oninput="App.attack.search(this.value)"></div><div class="table-wrap"><table><thead><tr><th>任务 / 轮次</th><th>靶标</th><th>蓝队策略</th><th>状态</th><th>攻破率</th><th>操作</th></tr></thead><tbody id="attack-task-rows">${X.taskRows(X.filteredTasks())}</tbody></table></div></section>`;};
X.filteredTasks=()=>X.db.tasks.filter(t=>(X.filter==='all'||X.filter===t.status)&&(t.name+X.targetFor(t).name+t.id).toLowerCase().includes(X.query.toLowerCase()));
X.search=v=>{X.query=v;document.getElementById('attack-task-rows').innerHTML=X.taskRows(X.filteredTasks());};
X.taskRows=rows=>rows.map(t=>`<tr><td><button class="link-btn" onclick="App.attack.open('${t.id}')"><strong>${E(t.name)}</strong></button><small>第 ${t.iteration||1} 轮 · ${E(t.created)}</small></td><td>${E(X.targetFor(t).name)}</td><td>${X.blueLabel(defense(t))}</td><td>${X.status(t)}<small>${X.metrics(t).done} / ${t.units.length}</small></td><td>${X.metrics(t).valid?X.metrics(t).asr+'%':'—'}</td><td><div class="flex"><button class="link-btn" onclick="App.attack.showArena('${t.id}')">演练场</button><button class="link-btn" onclick="App.attack.repeatTask('${t.id}',true)">再演练</button><button class="link-btn" onclick="App.attack.compare('${t.id}')">对比</button></div></td></tr>`).join('')||'<tr><td colspan="6" class="empty">暂无匹配任务</td></tr>';

X.newTask=function(){const defaults=X.db.defaults;X.selected=null;X.tab='create';X.wizard={step:1,name:'',description:'',scenes:[],methods:[],bankId:B.db[0]?.id||'',model:'',attacker:defaults.attacker||'',judge:defaults.judge||'',defenseMode:'existing',defensePrompt:'',maxRounds:4,concurrency:4,targetOutput:'',optimizationSteps:100,figHelper:false};X.wizardModal();window.scrollTo({top:0,behavior:'instant'});};
X.repeatTask=function(id,adjust){const t=X.db.tasks.find(t=>t.id===id);if(!t)return;X.newTask();Object.assign(X.wizard,{parentId:id,name:t.name,description:t.description||'',scenes:[...t.scenes].filter(id=>X.scene(id)),methods:[...(t.engine.methods||[...new Set(t.units.map(u=>u.method))])].filter(n=>M[n]),bankId:B.get(t.bankSnapshot?.id)?t.bankSnapshot.id:B.db[0]?.id||'',model:C.db.some(m=>m.id===t.model)?t.model:'',attacker:t.engine.roles?.attacker?.id||X.db.defaults.attacker,judge:t.engine.roles?.judge?.id||X.db.defaults.judge,defenseMode:defense(t).mode,defensePrompt:defense(t).prompt,maxRounds:t.engine.maxRounds||4,concurrency:t.engine.concurrency||4,targetOutput:t.engine.whitebox?.targetOutput||'',optimizationSteps:t.engine.whitebox?.steps||100,figHelper:!!t.engine.figHelper,step:adjust?1:4});X.reconcile();X.wizardModal();};
X.reconcile=function(){const w=X.wizard;if(w.model&&!X.methodFit(X.model(w.model),w))w.model='';if(w.defenseMode==='prompt'&&(!w.model||!X.canPrompt(X.model(w.model))))w.defenseMode='existing';};
X.toggleScene=function(id){const w=X.wizard,s=X.scene(id);if(!s)return;if(w.scenes.includes(id)){w.scenes=w.scenes.filter(x=>x!==id);w.methods=w.methods.filter(n=>!s.methods.includes(n));}else{w.scenes.push(id);w.methods=[...new Set([...w.methods,...s.methods])];}X.reconcile();X.wizardModal();};
X.toggleMethod=function(n){const w=X.wizard;if(!M[n])return;w.methods=w.methods.includes(n)?w.methods.filter(x=>x!==n):[...w.methods,n];X.reconcile();X.wizardModal();};
X.wizardTarget=function(id){X.wizard.model=id;X.reconcile();X.wizardModal();};
X.wizardModal=function(){const w=X.wizard,m=X.model(w.model),req=X.requirements(w.methods,w.figHelper);const field=(id,title,value,code,type='text')=>`<div class="field"><label for="${id}">${title}</label><input id="${id}" type="${type}" ${type==='number'?'min="1" step="1"':''} value="${E(value)}" oninput="${code}"></div>`;let body='';
const stepper=`<div class="exercise-steps">${['定义任务','题库与攻击场景','配置攻防角色','确认并启动'].map((s,i)=>`<div class="${w.step===i+1?'active':w.step>i+1?'done':''}"><b>${w.step>i+1?'✓':i+1}</b><span>${s}</span></div>`).join('')}</div>`;
if(w.step===1)body=`${w.parentId?`<div class="exercise-parent">基于 ${E(X.db.tasks.find(t=>t.id===w.parentId)?.name)} 再演练 · 自动保留上一轮配置</div>`:''}${field('task-name','任务名称 *',w.name,'App.attack.wizard.name=this.value')}<div class="field"><label for="task-description">任务描述</label><textarea id="task-description" rows="4" maxlength="1000" placeholder="例如：验证新增防御提示词后，多轮诱导风险是否降低" oninput="App.attack.wizard.description=this.value">${E(w.description)}</textarea></div>`;
if(w.step===2)body=`<section class="exercise-role"><h3 class="exercise-section-title">演练题库</h3><div class="field"><label for="task-bank">选择题库 *</label><select id="task-bank" onchange="App.attack.wizard.bankId=this.value;App.attack.wizardModal()">${B.db.map(b=>`<option value="${E(b.id)}" ${b.id===w.bankId?'selected':''}>${E(b.name)} · ${b.items.length} 题</option>`).join('')}</select></div>${X.bankPreview(w.bankId)}</section><section class="exercise-role"><h3 class="exercise-section-title">攻击场景</h3><div class="exercise-scenes">${X.scenarios.map(s=>`<section class="exercise-scene ${w.scenes.includes(s.id)?'selected':''}"><label class="exercise-scene-label"><input type="checkbox" ${w.scenes.includes(s.id)?'checked':''} onchange="App.attack.toggleScene('${s.id}')"><strong>${E(s.name)}</strong><span>${s.methods.length} 种方法</span></label>${w.scenes.includes(s.id)?`<div class="exercise-methods">${s.methods.map(n=>`<label><input type="checkbox" ${w.methods.includes(n)?'checked':''} onchange="App.attack.toggleMethod('${n}')"><span>${E(M[n].label)} <small>${n}</small></span><em>${n==='NanoGCG'?'需模型权重':M[n].gen?'需攻击模型':'无需攻击模型'}</em></label>`).join('')}</div>`:''}</section>`).join('')}</div></section>${w.methods.includes('NanoGCG')&&w.methods.includes('FigStep')?'<p class="error-message">白盒文本攻击与图片攻击请分为两个任务</p>':''}`;
if(w.step===3){const candidates=X.eligibleTargets(w);body=`<section class="exercise-role"><div class="exercise-role-title"><b>靶标</b><h3>靶标配置</h3></div><div class="field"><label for="task-model">靶标 *</label><select id="task-model" onchange="App.attack.wizardTarget(this.value)"><option value="">请选择靶标</option>${candidates.map(x=>`<option value="${x.id}" ${x.id===w.model?'selected':''}>${E(x.name)} · ${x.accessType==='weights'?'模型权重':'API 服务'}</option>`).join('')}</select></div>${!candidates.length?'<p class="error-message">暂无匹配连接，请先在模型接入中配置</p>':''}</section><section class="exercise-role red"><div class="exercise-role-title"><b>红队</b><h3>攻击生成</h3></div>${w.methods.includes('FigStep')?`<label class="setup-checkbox"><input type="checkbox" ${w.figHelper?'checked':''} onchange="App.attack.wizard.figHelper=this.checked;App.attack.wizardModal()">图片攻击启用辅助改写</label>`:''}${req.attacker?`<div class="field"><label for="task-attacker">攻击模型 *</label>${C.roleSelect('attacker',w.attacker,'task-attacker','App.attack.wizard.attacker=this.value')}</div><p class="exercise-note">推荐候选：DeepSeek-V3，需使用自己的服务和调用额度</p>`:'<p class="exercise-note">所选方法通过模板或规则生成输入，无需攻击模型</p>'}</section><section class="exercise-role"><div class="exercise-role-title"><b>蓝队</b><h3>蓝队策略</h3></div>${X.blueEditor(w)}</section><section class="exercise-role judge"><div class="exercise-role-title"><b>评价</b><h3>评价模型</h3></div><div class="field"><label for="task-judge">评价模型 *</label>${C.roleSelect('judge',w.judge,'task-judge','App.attack.wizard.judge=this.value')}</div></section>`;}
if(w.step===4){const bank=B.get(w.bankId);body=`<div class="exercise-summary">${[['任务名称',w.name],['任务描述',w.description||'—'],['靶标',m.name],['蓝队策略',X.blueLabel(X.blueSnapshot(w))],...(w.defenseMode==='prompt'?[['防御提示词',w.defensePrompt]]:[]),['攻击模型',req.attacker?X.model(w.attacker).name:'不需要'],['评价模型',X.model(w.judge).name],['题库',`${bank?.name||'未选择'} · ${bank?.items.length||0} 题`]].map(([k,v])=>`<div class="kv"><span>${k}</span><strong>${E(v)}</strong></div>`).join('')}${w.scenes.map(id=>`<div class="kv"><span>${E(X.scene(id)?.name)}</span><span>${w.methods.filter(n=>X.scene(id)?.methods.includes(n)).map(n=>E(M[n].label)).join('、')}</span></div>`).join('')}</div>${X.blueEvidenceHTML(X.blueSnapshot(w))}<div class="exercise-total">计划测试 <strong>${(bank?.items.length||0)*w.methods.length}</strong> 个单元</div><div class="form-grid">${field('engine-concurrency','并发测试单元',w.concurrency,'App.attack.wizard.concurrency=Number(this.value)','number')}${req.process?field('engine-rounds','迭代方法最大轮数',w.maxRounds,'App.attack.wizard.maxRounds=Number(this.value)','number'):''}</div>${w.methods.includes('NanoGCG')?`<h3 class="exercise-section-title">白盒攻击参数</h3>${field('whitebox-target','目标输出 *',w.targetOutput,'App.attack.wizard.targetOutput=this.value')}${field('whitebox-steps','优化步数 *',w.optimizationSteps,'App.attack.wizard.optimizationSteps=Number(this.value)','number')}`:''}<p class="exercise-note">模拟执行，不调用真实模型、不消耗 Token；本次配置将保存为快照</p>`;}
X.presentWizard(stepper+body+'<p id="wizard-error" class="error-message" role="alert"></p>',`<span class="muted">${w.step} / 4</span><div class="flex"><button class="btn" onclick="${w.step===1?"App.attack.setTab('arena')":'App.attack.wizard.step--;App.attack.wizardModal()'}">${w.step===1?'取消':'上一步'}</button><button class="btn primary" onclick="App.attack.wizardNext()">${w.step===4?'启动模拟演练':'下一步'}</button></div>`);
};
X.taskValidation=function(w){if(!w.name.trim())return '请填写任务名称';if(w.name.length>100)return '任务名称不能超过 100 个字符';if(w.step===1)return '';if(!w.methods.length||!w.scenes.length)return '请选择攻击场景和方法';if(w.methods.some(n=>!M[n]||!w.scenes.some(id=>X.scene(id)?.methods.includes(n))))return '存在不匹配的攻击方法';if(w.scenes.some(id=>!X.scene(id)||!X.scene(id).methods.some(n=>w.methods.includes(n))))return '每个场景至少选择一种方法，或取消该场景';if(w.methods.includes('NanoGCG')&&w.methods.includes('FigStep'))return '请将白盒文本攻击与图片攻击分为两个任务';if(!B.get(w.bankId)?.items.length)return '请选择有效题库';if(w.step===2)return '';const m=C.db.find(m=>m.id===w.model);if(!X.methodFit(m,w))return '请选择与攻击方法匹配的靶标';if(w.defenseMode==='prompt'&&(!X.canPrompt(m)||!w.defensePrompt.trim()))return '请填写防御提示词，并使用支持该配置的模型连接';const blueError=X.validateBlue(w);if(blueError)return blueError;const req=X.requirements(w.methods,w.figHelper);for(const r of ['judge',...(req.attacker?['attacker']:[])])if(!C.eligible(r).some(m=>m.id===w[r]))return `请选择${r==='judge'?'评价模型':'攻击模型'}`;if(w.step===3)return '';if(!Number.isSafeInteger(w.concurrency)||w.concurrency<1||w.concurrency>8)return '并发测试单元需为 1–8 的整数';if(req.process&&(!Number.isSafeInteger(w.maxRounds)||w.maxRounds<1))return '最大轮数需为大于 0 的整数';if(w.methods.includes('NanoGCG')&&(!w.targetOutput.trim()||!Number.isSafeInteger(w.optimizationSteps)||w.optimizationSteps<1))return '请填写目标输出和正整数优化步数';return '';};
X.connectionSnapshot=m=>m?Object.fromEntries(['id','name','model','endpoint','protocol','provider','botId','userId','kind','accessType','node','modelPath','tokenizerPath','caps'].filter(k=>m[k]!==undefined).map(k=>[k,copy(m[k])])):null;
X.wizardNext=function(){const w=X.wizard,error=X.taskValidation(w);if(error){document.getElementById('wizard-error').textContent=error;return;}if(w.step<4){w.step++;X.wizardModal();return;}const req=X.requirements(w.methods,w.figHelper),target=X.model(w.model),judge=X.model(w.judge),attacker=req.attacker?X.model(w.attacker):null,bank=B.get(w.bankId);const engine={attacker:attacker?attacker.name:'规则 / 模板生成',judge:judge.name,concurrency:w.concurrency,maxRounds:req.process?w.maxRounds:1,methods:[...w.methods],figHelper:!!w.figHelper,roles:{attacker:X.connectionSnapshot(attacker),judge:X.connectionSnapshot(judge)},evaluationVersion:'unified-v1',bindings:w.methods.map(n=>({method:n,registry:X.methodInfo[n][0],generator:M[n].gen||(n==='FigStep'&&w.figHelper)?attacker.id:null,judge:judge.id})),...(w.methods.includes('NanoGCG')?{whitebox:{targetOutput:w.targetOutput.trim(),steps:w.optimizationSteps,simulated:true}}:{})};const t=X.makeTask(w.name.trim(),w.model,w.scenes,'dataset',bank.items.length,engine);t.id='EV-'+safeId();t.description=w.description.trim();t.defense=X.blueSnapshot(w);t.targetSnapshot=X.connectionSnapshot(target);t.bankSnapshot={id:bank.id,name:bank.name,items:copy(bank.items)};t.units.forEach((u,i)=>{u.questionId=bank.items[i%bank.items.length].id;u.rounds=M[u.method].process?w.maxRounds:1;});const parent=X.db.tasks.find(t=>t.id===w.parentId);t.parentId=parent?.id||null;t.seriesId=parent?.seriesId||parent?.id||t.id;t.iteration=parent?Math.max(...X.db.tasks.filter(x=>(x.seriesId||x.id)===t.seriesId).map(x=>x.iteration||1))+1:1;t.changeSummary=parent?X.changes(parent,t).join('、')||'配置不变，再次运行':'首次演练';t.simulated=true;X.db.tasks.unshift(t);A.save();X.showArena(t.id);A.toast('模拟攻防任务已启动');};
X.changes=function(a,b){const r=[];if(JSON.stringify(X.targetFor(a))!==JSON.stringify(X.targetFor(b)))r.push('调整靶标');if(JSON.stringify(defense(a))!==JSON.stringify(defense(b)))r.push('调整蓝队策略');if(JSON.stringify((a.engine.methods||[...new Set(a.units.map(u=>u.method))]).slice().sort())!==JSON.stringify(b.engine.methods.slice().sort()))r.push('调整攻击方法');if(JSON.stringify(a.bankSnapshot?.items)!==JSON.stringify(b.bankSnapshot?.items))r.push('调整题库');if(JSON.stringify(a.engine.roles?.judge)!==JSON.stringify(b.engine.roles?.judge))r.push('调整评价模型');if(a.engine.maxRounds!==b.engine.maxRounds||JSON.stringify(a.engine.whitebox)!==JSON.stringify(b.engine.whitebox)||a.engine.figHelper!==b.engine.figHelper||a.engine.concurrency!==b.engine.concurrency)r.push('调整执行参数');if(JSON.stringify(a.engine.roles?.attacker)!==JSON.stringify(b.engine.roles?.attacker))r.push('调整攻击模型');return r;};
X.comparable=function(a,b){if(!a.bankSnapshot||!b.bankSnapshot||!a.engine.evaluationVersion||!b.engine.evaluationVersion)return false;return JSON.stringify([a.bankSnapshot.items,(a.engine.methods||[]).slice().sort(),a.engine.roles?.judge,a.engine.evaluationVersion,a.engine.maxRounds,a.engine.concurrency,a.engine.whitebox,a.engine.figHelper,a.engine.roles?.attacker])===JSON.stringify([b.bankSnapshot.items,(b.engine.methods||[]).slice().sort(),b.engine.roles?.judge,b.engine.evaluationVersion,b.engine.maxRounds,b.engine.concurrency,b.engine.whitebox,b.engine.figHelper,b.engine.roles?.attacker]);};
X.compare=function(id){const t=X.db.tasks.find(t=>t.id===id);if(!t)return;const rows=X.db.tasks.filter(x=>(x.seriesId||x.id)===(t.seriesId||t.id)).sort((a,b)=>(a.iteration||1)-(b.iteration||1));const base=rows[0];A.modal('演练轮次对比',`<p class="exercise-note">同系列演练 · ${E(base.name)}</p><div class="table-wrap"><table><thead><tr><th>轮次</th><th>变更</th><th>状态</th><th>完成 / 总量</th><th>攻破率</th><th>与首轮可比性</th></tr></thead><tbody>${rows.map((r,i)=>{const m=X.metrics(r);return `<tr><td>第 ${r.iteration||1} 轮</td><td>${E(r.changeSummary||'首次演练')}</td><td>${X.status(r)}</td><td>${m.done} / ${m.total}</td><td>${m.valid?m.asr+'%':'—'}</td><td>${i===0?'基准轮次':!X.comparable(base,r)?'测试配置不同':base.status!=='done'||r.status!=='done'?'结果未完成':'测试配置一致'}</td></tr>`;}).join('')}</tbody></table></div><p class="exercise-note">模拟结果仅用于演示流程，不代表防御措施的真实收益</p>`,`<button class="btn" onclick="App.closeModal()">关闭</button>`,{wide:true});};
const previousConfig=X.config;X.config=function(t){return `<section class="card exercise-task-meta"><div class="card-body"><div class="kv"><span>任务描述</span><span>${E(t.description||'—')}</span></div><div class="kv"><span>演练轮次</span><span>第 ${t.iteration||1} 轮 · ${E(t.changeSummary||'首次演练')}</span></div><div class="kv"><span>蓝队策略</span><span>${X.blueLabel(defense(t))}</span></div>${defense(t).prompt?`<div class="kv"><span>防御提示词</span><span style="white-space:pre-wrap">${E(defense(t).prompt)}</span></div>`:''}<div class="flex"><button class="btn small" onclick="App.attack.showArena('${t.id}')">进入演练场</button><button class="btn small" onclick="App.attack.repeatTask('${t.id}',true)">调整后再演练</button><button class="btn small" onclick="App.attack.compare('${t.id}')">轮次对比</button></div></div></section>`+previousConfig(t);};
X.sample=function(id){const t=X.task,u=t.units.find(u=>u.id===id);if(!u)return;const c=X.unitContent(t,u);A.drawer(`攻击记录 · ${u.id}`,`${A.badge(resultName(u),u.result==='breach'?'orange':'blue')}<div class="exercise-record"><h3>攻击输入 · ${E(u.method)}</h3><pre>${E(c.prompt)}</pre><h3>蓝队响应</h3><pre>${E(c.response)}</pre><h3>评价结果</h3><p>${E(c.verdict)}</p><div class="kv"><span>评价模型</span><span>${E(t.engine.judge)}</span></div><div class="kv"><span>蓝队策略</span><span>${X.blueLabel(defense(t))}</span></div></div>`,`<button class="btn" onclick="App.closeDrawer()">关闭</button><button class="btn primary" onclick="App.attack.exportOne('${u.id}')">导出记录</button>`);};
const previousDetail=X.detail;X.detail=function(){return previousDetail().replaceAll('最终 Judge','评价模型').replaceAll('最终评价确认','评价确认').replaceAll('返回演练列表','返回任务管理');};
const beforeReport=X.reportHTML;X.reportHTML=function(){const t=X.task;const html=beforeReport();return html.replaceAll('最终 Judge','评价模型').replace('</html>',`<section><h2>演练配置</h2><p>第 ${t.iteration||1} 轮 · ${E(t.changeSummary||'首次演练')}</p><p>任务描述：${E(t.description||'—')}</p><p>蓝队策略：${X.blueLabel(defense(t))}</p>${defense(t).prompt?`<pre>${E(defense(t).prompt)}</pre>`:''}</section></html>`);};
})();
