(function () {
'use strict';
const A=window.App, X=A.attack, E=A.escape, I=A.icon, scenes=X.scenarios;
const roles={target:'被测对象',attacker:'攻击生成',judge:'Judge 评价'};
// Dependency mapping follows the bundled OpenRT implementation, not the algorithm name alone.
const methods={
 Direct:{label:'直接提问',gen:false,process:false,note:'原样发送测试样本，建立基线'},
 DeepInception:{label:'嵌套情境',gen:false,process:false,note:'使用固定情境模板'},
 PAIR:{label:'反馈式改写',gen:true,process:true,param:'attacker_model',note:'攻击模型根据回应迭代，过程裁判决定是否继续'},
 Crescendo:{label:'渐进式追问',gen:true,process:true,param:'attack_model',note:'在多轮会话中逐步生成追问'},
 CoA:{label:'分步诱导',gen:true,process:true,param:'attack_model',note:'生成并执行多轮测试步骤'},
 CipherChat:{label:'编码表达',gen:false,process:false,note:'使用编码规则与示例，无需辅助模型'},
 Multilingual:{label:'跨语言测试',gen:true,process:false,param:'helper_model',note:'攻击生成模型承担翻译工作'},
 FlipAttack:{label:'字符重排',gen:false,process:false,note:'使用本地字符变换规则'},
 PastTense:{label:'时态改写',gen:true,process:false,param:'reformulation_model',note:'攻击生成模型承担改写工作；当前采用单次改写模式'},
 FigStep:{label:'图片文字指令',gen:false,process:false,param:'helper_model',note:'默认直接渲染文字；可按需开启辅助改写被测对象须支持图像'},
 NanoGCG:{label:'梯度优化',gen:false,process:false,note:'需要权重、tokenizer、梯度与 GPU；仅接入本地 URL 不满足条件'},
};
X.methodDependencies=methods;
const C=A.connections={
 secrets:new Map(),draft:null,returnTo:null,
 get db(){return X.db.models},
 init(){
  const retired=X.db.models.filter(m=>m.accessType==='weights');
  if(retired.length){X.db.retiredWeightConnections=[...(X.db.retiredWeightConnections||[]),...retired];X.db.models=X.db.models.filter(m=>m.accessType!=='weights');}
  for(const m of C.db){
   m.accessType ||= 'api';if(!m.schema){m.sample=['m1','m2','m3'].includes(m.id);m.kind='model';m.hosting='cloud';m.protocol='openai';m.auth='bearer';m.uses=['target'];m.timeout=60;m.schema=2;}
   if(m.connectStatus===undefined)m.connectStatus=(m.sample||m.auth==='none')?'ok':'pending';
   // Old versions never asked for credentials. Never import credentials into browser storage.
   delete m.apiKey;delete m.key;delete m.token;
  }
  X.db.defaults ||= {attacker:'',judge:'',processMode:'reuse',process:''};
 },
 clearSecrets(){C.secrets.clear();C.draft=null;const el=document.getElementById('c-key');if(el)el.value='';},
 ready(m){return !!m;},
 connState(m){if(m.presetPending)return {label:'待配置',tone:'orange',ok:false};if(m.connectStatus==='testing')return {label:'测试中',tone:'blue',testing:true};if(m.sample||m.auth==='none'||C.secrets.has(m.id)||m.connectStatus==='ok')return {label:'已连通',tone:'green',ok:true};return {label:'未连通',tone:'gray',ok:false};},
 status(m){return C.connState(m).label;},
 usedBy(id){return X.db.tasks.filter(t=>t.model===id||Object.values(t.engine.roles||{}).some(r=>r&&r.id===id));},
 test(id){const m=C.db.find(x=>x.id===id);if(!m)return;
  if(m.presetPending){A.toast('该连接尚未配置，请先编辑再测试');return;}
  if(m.connectStatus==='testing')return;
  // Decide the outcome first, then only the status tag changes: 未连通 -> 测试中 -> 已连通/未连通. No modal.
  const ok=m.sample||m.auth==='none'||C.secrets.has(m.id)||m.connectStatus==='ok';
  m.connectStatus='testing';A.save();A.render();
  setTimeout(()=>{m.connectStatus=ok?'ok':'fail';A.save();A.render();A.toast(ok?'连接测试成功':'连接测试失败：缺少 API Key');},800);},
 remove(id){const m=C.db.find(x=>x.id===id);if(!m)return;
  const noun=m.kind==='agent'?'智能体':'模型';
  A.modal('删除'+noun,`<p>确认删除${noun}「${E(m.name)}」吗？</p>`,`<button class="btn" onclick="App.closeModal()">取消</button><button class="btn danger" onclick="App.connections.removeConfirm('${m.id}')">删除</button>`,{plain:true});},
 removeConfirm(id){const at=C.db.findIndex(x=>x.id===id);if(at<0){A.closeModal();return;}const m=C.db[at];C.db.splice(at,1);C.secrets.delete(id);for(const r of ['attacker','judge','process'])if(X.db.defaults?.[r]===id)X.db.defaults[r]='';A.save();A.closeModal();A.render();A.toast(`已删除「${m.name}」`);},
 eligible(){return C.db.filter(m=>(m.kind||'model')==='model'&&m.accessType!=='weights');},
 options(role,value){return '<option value="">请选择连接</option>'+C.eligible(role).map(m=>`<option value="${m.id}" ${value===m.id?'selected':''}>${E(m.name)}${m.accessType==='weights'?' · 模型权重':''}</option>`).join('');},
 roleSelect(role,value,id,onchange){return `<select id="${id}" onchange="${onchange}">${C.options(role,value)}</select>`;},
 open(id='',role='target',preset='',returnTo=null){
  const m=C.db.find(x=>x.id===id);
  C.returnTo=returnTo;C.role=role;
  C.draft=m?{...m,caps:[...m.caps],uses:[...m.uses],key:'',tested:false}:{id:'',name:'',vendor:'',kind:X.connectionKind||'model',hosting:'cloud',protocol:'openai',model:'',endpoint:'',auth:'bearer',header:'X-API-Key',caps:['text','chat'],uses:[role],timeout:60,body:'{"input":"{{input}}"}',responsePath:'output',sessionPath:'session_id',key:'',tested:false};
  if(m?.sample){C.draft.id='';C.draft.sample=false;C.draft.endpoint='';C.draft.name=m.name+' · 自有接入';}
  if(preset==='v3')Object.assign(C.draft,{name:'DeepSeek-V3 · 攻击生成',hosting:'local',model:'',endpoint:'',uses:['attacker'],recommendation:'v3'});
  if(preset==='judge')Object.assign(C.draft,{name:'DeepSeek-V4-Flash · Judge',model:'deepseek-v4-flash',endpoint:'https://api.deepseek.com',uses:['judge'],thinking:true,recommendation:'judge'});
  C.form();
 },
 capture(){const d=C.draft;for(const n of ['name','vendor','endpoint','key']){const el=document.getElementById('c-'+n);if(el)d[n]=el.value;}d.uses=d.kind==='agent'?['target']:['target','attacker','judge'];d.caps=['text','chat'];d.timeout=60;d.auth=d.key.trim()||C.secrets.has(d.id)?'bearer':'none';d.hosting=/^https?:\/\/(localhost|127\.0\.0\.1|\[::1\])(?=[:/]|$)/i.test(d.endpoint)?'local':'cloud';},
 change(){C.capture();C.form();},
 markDirty(){if(!C.draft)return;C.draft.tested=false;const btn=document.getElementById('c-test-btn');if(btn){btn.classList.remove('ok');btn.innerHTML=`${I('zap',14)}测试链接`;}},
 form(){const d=C.draft;const f=(id,label,value,placeholder='',type='text',extra='')=>`<div class="field"><label for="c-${id}">${label}</label><input id="c-${id}" type="${type}" value="${E(value||'')}" placeholder="${placeholder}" autocomplete="off" ${extra}></div>`;
  A.modal(d.id?'编辑连接':d.kind==='agent'?'接入智能体':'接入模型',`<form id="connection-form" onsubmit="return false">${f('name','模型名称 *',d.name,'例如：测试模型')}${f('vendor','厂商',d.vendor,'例如：DeepSeek')}${f('endpoint','Base URL *',d.endpoint,'填写服务地址','text','oninput="App.connections.markDirty()"')}<div class="field"><label for="c-key">API Key *</label><div class="field-row"><input id="c-key" type="password" value="${E(d.key||'')}" placeholder="${C.secrets.has(d.id)?'留空保留已保存的密钥':'填写服务调用的 API Key'}" autocomplete="off" oninput="App.connections.markDirty()"><button class="btn" type="button" id="c-test-btn" onclick="App.connections.testDraft()">${I('zap',14)}测试链接</button></div></div><p id="connection-error" class="error-message" role="alert"></p></form>`,`<button class="btn" onclick="App.connections.cancel()">取消</button><button class="btn primary" onclick="App.connections.save()">保存配置</button>`,{wide:false});},
 validate(d){if(!d.name.trim())return '请填写模型名称';if(!d.endpoint.trim())return '请填写 Base URL';if(!d.key.trim()&&!C.secrets.has(d.id))return '请填写 API Key';return '';},
 check(){C.capture();const error=C.validate(C.draft);const errEl=document.getElementById('connection-error');if(errEl)errEl.textContent=error;return !error;},
 testDraft(){C.capture();const d=C.draft,error=C.validate(d),errEl=document.getElementById('connection-error'),btn=document.getElementById('c-test-btn');
  if(error){if(errEl){errEl.textContent=error;errEl.scrollIntoView?.({block:'nearest'});}return;}
  if(errEl)errEl.textContent='';
  // Feedback lives on the inline button only: 测试中… -> green ✓ 已通过.
  if(btn){btn.disabled=true;btn.classList.remove('ok');btn.textContent='测试中…';}
  setTimeout(()=>{if(!btn||!btn.isConnected)return;
   d.tested=true;if(btn){btn.disabled=false;btn.classList.add('ok');btn.textContent='✓ 已通过';}
   A.toast('连接测试成功');},800)},
 save(){
  C.capture();const d=C.draft;
  if(!d.tested){const errEl=document.getElementById('connection-error');if(errEl){errEl.textContent='请先完成连通性测试，再保存配置';errEl.scrollIntoView?.({block:'nearest'});}return;}
  if(!C.check())return;const id=d.id||'conn-'+Date.now()+'-'+Math.random().toString(36).slice(2,6);
  // Whitelist metadata: no credential or draft object is serialized.
  const m={id,accessType:d.kind==='agent'?'api':d.accessType||'api',schema:2,sample:false,name:d.name.trim(),kind:d.kind,hosting:d.hosting,protocol:d.protocol,model:d.protocol==='http'?'HTTP 智能体':d.model.trim(),endpoint:d.endpoint.trim().replace(/\/$/,''),auth:d.auth,header:d.auth==='header'?d.header:'',caps:[...d.caps],uses:[...d.uses],timeout:d.timeout,thinking:d.protocol==='openai'&&!!d.thinking,vendor:(d.vendor||'').trim(),desc:d.kind==='agent'?'自有智能体接入':'自有模型接入',connectStatus:(d.key.trim()||C.secrets.has(id))?'ok':'pending'};
  if(m.accessType==='weights'){Object.assign(m,{node:d.node.trim(),modelPath:d.modelPath.trim(),tokenizerPath:d.tokenizerPath?.trim()||d.modelPath.trim(),protocol:'huggingface',model:d.name.trim(),endpoint:'',auth:'none',hosting:'local',validationStatus:'unverified'});d.auth='none';}
  if(d.protocol==='http'&&m.accessType!=='weights')Object.assign(m,{body:d.body,responsePath:d.responsePath,sessionPath:d.body.includes('{{session_id}}')?d.sessionPath:''});
  if(d.auth==='none')C.secrets.delete(id);else if(d.key.trim())C.secrets.set(id,d.key.trim());
  const at=C.db.findIndex(x=>x.id===id);if(at>=0)C.db[at]=m;else C.db.push(m);
  const rt=C.returnTo,role=C.role;C.draft=null;document.getElementById('c-key')?.setAttribute('value','');const input=document.getElementById('c-key');if(input)input.value='';
  A.save();A.closeModal();
  if(rt==='wizard'){X.wizard[role==='target'?'model':role]=id;X.wizardModal();}
  else if(rt==='settings'){X.settingsDraft[role]=id;X.tab='settings';A.render();}
  else{X.tab='models';X.selected=null;A.render();}
  A.toast('配置成功');
 },
 cancel(){const rt=C.returnTo;C.draft=null;const input=document.getElementById('c-key');if(input){input.value='';input.setAttribute('value','');}A.closeModal();if(rt==='wizard')X.wizardModal();}
};
const originalInit=X.init;
X.init=function(){originalInit();C.init();};
for(const [name,m] of Object.entries(methods))X.methodInfo[name][2]=`${m.gen?'攻击生成模型 + ':''}最终 Judge${m.process?'；过程裁判（默认复用 Judge）':''}${name==='FigStep'?'；辅助改写可选':''}${['NanoGCG'].includes(name)?'；'+m.note:''}`;
Object.assign(X,{
 requirements(names,figHelper=false){return {attacker:names.some(n=>methods[n].gen||(n==='FigStep'&&figHelper)),process:names.some(n=>methods[n].process),judge:names.length>0};},
 overview(){if(X.tab==='banks')return A.heading('','题库管理','')+A.banks.render();if(X.tab==='create')return A.heading('','新建演练任务','')+(X.creationHTML||'');const tasks=X.db.tasks,running=tasks.filter(t=>t.status==='running'),totals=tasks.reduce((s,t)=>{const m=X.metrics(t);s.done+=m.done;s.breach+=m.breach;return s},{done:0,breach:0});
  return A.heading('RED TEAM EVALUATION',({tasks:'演练任务',results:'演练结果',scenarios:'攻击方法库',models:'模型与智能体接入',settings:'演练配置'}[X.tab]||'演练任务'),({tasks:'',results:'查看演练结果、风险证据与报告',models:'管理服务连接与凭据，为被测对象和演练角色提供模型资产',settings:'指定攻击模型与 Judge，创建任务时按方法依赖应用',scenarios:'从业务风险选择测试方法，查看适用条件与模型依赖'}[X.tab]),'')+
  `<div class="tabs center-page-tabs">${[['tasks','演练任务'],['scenarios','攻击场景'],['models','模型与智能体接入'],['settings','演练配置']].map(([id,label])=>`<button class="tab ${X.tab===id?'active':''}" onclick="App.attack.setTab('${id}')">${label}</button>`).join('')}</div>`+
  (X.tab==='tasks'?X.dashboard()+X.taskList():X.tab==='results'?X.results():X.tab==='scenarios'?X.catalog():X.tab==='models'?X.models():X.settings());
 },
 results(){const tasks=X.db.tasks.filter(t=>X.metrics(t).done>0);return `<div class="card"><div class="card-head"><h3 class="card-title">演练结果与报告 <span class="mini-tag">${tasks.length}</span></h3><span class="muted small-text">进行中的任务显示阶段结果</span></div><div class="table-wrap"><table><thead><tr><th>演练任务</th><th>被测对象</th><th>任务状态</th><th>已确认风险</th><th>攻击成功率</th><th>操作</th></tr></thead><tbody>${tasks.map(t=>{const m=X.metrics(t);return `<tr><td><strong>${E(t.name)}</strong><small>${E(t.id)}</small></td><td>${E(X.targetFor(t).name)}</td><td>${X.status(t)}</td><td>${m.breach}</td><td>${m.asr}%</td><td><button class="link-btn" onclick="App.attack.open('${t.id}');App.attack.detailTab='report';App.render()">查看结果</button></td></tr>`}).join('')||'<tr><td colspan="6"><div class="empty">完成测试后将在此显示结果</div></td></tr>'}</tbody></table></div></div>`;},
 connectionKind:'model',
 models(){const kind=X.connectionKind||'model',items=C.db.filter(m=>(m.kind||'model')===kind);return `<div class="setup-page-head"><div class="tabs connection-kind-tabs"><button class="tab ${kind==='model'?'active':''}" onclick="App.attack.connectionKind='model';App.render()">模型</button><button class="tab ${kind==='agent'?'active':''}" onclick="App.attack.connectionKind='agent';App.render()">智能体</button></div><button class="btn primary" onclick="App.connections.open()">${I('plus',14)}${kind==='model'?'接入模型':'接入智能体'}</button></div><div class="attack-model-grid">${items.map(m=>{const st=C.connState(m);return `<article class="card attack-model-card"><div class="attack-model-head"><span class="model-mark">${I(m.kind==='agent'?'terminal':'box',19)}</span><div class="attack-model-title"><strong>${E(m.name)}</strong><small>${E(m.vendor||m.model||m.endpoint||(m.kind==='agent'?'智能体接入':'模型接入'))}</small></div><span class="badge ${st.tone} connection-state${st.testing?' testing':''}">${E(st.label)}</span></div><div class="attack-model-actions"><button class="model-action" title="编辑" aria-label="编辑 ${E(m.name)}" onclick="App.connections.open('${m.id}')">${I('edit',16)}</button><button class="model-action" title="测试连接" aria-label="测试 ${E(m.name)}" onclick="App.connections.test('${m.id}')">${I('zap',16)}</button><button class="model-action danger" title="删除" aria-label="删除 ${E(m.name)}" onclick="App.connections.remove('${m.id}')">${I('trash',16)}</button></div></article>`;}).join('')||'<div class="empty">暂无连接，点击右上角按钮接入</div>'}</div>`;},
 addModel(){C.open();},
 recommendation(role){return role==='attacker'?`<div class="role-recommend"><strong>推荐候选 · DeepSeek-V3</strong><p>用于测试输入生成、翻译或改写由您接入自己的 V3 服务，先用少量样本验证生成能力与适配性</p></div>`:`<div class="role-recommend"><strong>推荐候选 · DeepSeek-V4-Flash</strong><p>建议启用推理模式用于最终评价请先用标注样本校准判定质量，避免由被测模型自评</p><a href="https://api-docs.deepseek.com/" target="_blank" rel="noopener noreferrer">官方接入文档 ↗</a></div>`;},
 settings(){const d=X.settingsDraft ||= {...X.db.defaults};return `<div class="setup-page-head"><div><h2>演练角色默认配置</h2><p class="muted">这里只指定谁生成测试、谁评价结果具体连接统一在「模型与智能体接入」管理</p></div><button class="btn primary" onclick="App.attack.saveSettings()">保存默认配置</button></div><div class="setup-role-grid">${[['attacker','攻击模型','生成测试输入，按所选方法启用'],['judge','Judge 模型','评价被测对象的最终输出，每次演练必需']].map(([r,title,desc],i)=>`<section class="card setup-role-card"><div class="setup-role-number">0${i+1}</div><h3>${title}</h3><p class="muted">${desc}</p><div class="field section-gap"><label for="default-${r}">默认${title}</label>${C.roleSelect(r,d[r],'default-'+r,`App.attack.settingsDraft.${r}=this.value`)}</div>${X.recommendation(r)}</section>`).join('')}</div><div class="card setup-process"><div><h3>过程裁判</h3><p class="muted">仅 PAIR、渐进式追问、分步诱导需要用于决定如何继续攻击，不直接计入最终结果</p></div><div class="field"><label for="default-process-mode">模型来源</label><select id="default-process-mode" onchange="App.attack.settingsDraft.processMode=this.value;App.render()"><option value="reuse" ${d.processMode==='reuse'?'selected':''}>复用最终 Judge · 使用独立评价调用</option><option value="separate" ${d.processMode==='separate'?'selected':''}>单独指定过程裁判</option></select></div>${d.processMode==='separate'?`<div class="field"><label for="default-process">过程裁判连接</label>${C.roleSelect('judge',d.process,'default-process','App.attack.settingsDraft.process=this.value')}</div>`:''}</div><div class="setup-hint">默认配置可以留空；创建任务时会提示补齐实际需要的角色平台不预置可用密钥，也不赠送模型调用额度</div><div class="card"><div class="card-head"><h3 class="card-title">不同方法需要哪些模型？</h3></div>${X.dependencyTable(Object.keys(methods).filter(n=>!['NanoGCG'].includes(n)))}</div>`;},
 saveSettings(){const d=X.settingsDraft;for(const r of ['attacker','judge'])if(d[r]&&!C.eligible(r).some(m=>m.id===d[r])){A.toast('所选连接已不可用，请重新选择');return;}if(d.processMode==='separate'&&!C.eligible('judge').some(m=>m.id===d.process)){A.toast('请选择模型作为过程裁判');return;}X.db.defaults={...d};A.save();A.toast('默认角色已保存，新建任务时按需应用');},
 dependencyTable(names,figHelper=false){return `<div class="table-wrap"><table class="dependency-table"><thead><tr><th>测试方法</th><th>攻击生成</th><th>过程裁判</th><th>最终 Judge</th></tr></thead><tbody>${names.map(n=>{const m=methods[n],gen=m.gen||(n==='FigStep'&&figHelper);return `<tr><td><strong>${m.label}</strong><small>${E(n)} · ${m.note}</small></td><td>${gen?'需要':n==='FigStep'?'按需开启':'不需要'}</td><td>${m.process?'需要':'不需要'}</td><td>需要</td></tr>`;}).join('')}</tbody></table></div>`;},
 newTask(sid,mid){window.scrollTo({top:0,behavior:'instant'});X.selected=null;X.tab='create';const target=mid?X.model(mid):C.eligible('target').find(C.ready)||C.db.find(m=>m.sample),d=X.db.defaults;X.wizard={step:1,name:'',model:target?.id||'',scenes:[],methods:[],bankId:A.banks.db[0].id,level:'dataset',...d,processMode:'reuse',concurrency:4,maxRounds:4,figHelper:false,targetOutput:'',optimizationSteps:100};if(sid&&target&&X.sceneAvailable(X.scene(sid),target)){X.wizard.scenes=[sid];X.wizard.methods=[...X.scene(sid).methods];}X.wizardModal();},
 wizardTarget(id){X.wizard.model=id;X.wizard.scenes=[];X.wizard.methods=[];X.wizardModal();},
 wizardModal(){const w=X.wizard,m=X.model(w.model),req=X.requirements(w.methods,w.figHelper);let body='';
  const head=`<div class="attack-steps">${['选择被测对象','选择场景与方法','确认演练配置'].map((label,i)=>`<div class="attack-step ${w.step>=i+1?'active':''}"><i>${w.step>i+1?'✓':i+1}</i><span>${label}</span></div>`).join('')}</div>`;
  if(w.step===1)body=`<div class="field"><label for="task-name">演练任务名称 *</label><input id="task-name" value="${E(w.name)}" maxlength="60" placeholder="例如：模型发布前验证" oninput="App.attack.wizard.name=this.value"></div><div class="field"><div class="flex between"><label for="task-model">靶标 *</label></div><select id="task-model" onchange="App.attack.wizardTarget(this.value)">${C.options('target',w.model,true)}</select></div><div class="field"><label for="task-bank">演练题库 *</label><select id="task-bank" onchange="App.attack.wizard.bankId=this.value;App.attack.wizardModal()">${A.banks.db.map(b=>`<option value="${b.id}" ${w.bankId===b.id?'selected':''}>${E(b.name)} · ${b.items.length} 题</option>`).join('')}</select></div><div class="setup-target-preview"><h3>${E(m.name)}</h3><p class="hint">${m.id?C.status(m):'请先在模型接入中配置连接'}</p></div><p class="hint section-gap">这里只选择本次要测的对象；攻击生成与 Judge 在最后一步按需配置示例对象只可用于本地模拟</p>`;
  if(w.step===2)body=`<div class="attack-scenarios">${scenes.map(s=>{const able=X.sceneAvailable(s,m),sel=w.scenes.includes(s.id);return `<button class="attack-scenario ${sel?'selected':''}" ${able?'':'disabled'} onclick="App.attack.toggleScene('${s.id}')"><div class="scenario-top"><span class="scenario-check">${sel?'✓':''}</span></div><h3>${s.name}</h3><p>${s.desc}</p><small>${able?(s.need==='vision'?'需服务支持图像输入，执行时验证':s.use):s.boundary?s.need==='weights'?'需本地权重与执行器；URL 接入不适用':'需上下文注入适配器':s.need==='vision'?'被测对象需支持图像':'被测对象需支持多轮会话'}</small></button>`;}).join('')}</div>${w.scenes.length?`<details class="attack-advanced" ${w.methodsExpanded?'open':''} ontoggle="App.attack.wizard.methodsExpanded=this.open"><summary>调整测试方法 · 已选 ${w.methods.length} 种</summary>${w.scenes.map(id=>`<div class="method-group"><h4>${X.scene(id).name}</h4>${X.scene(id).methods.map(n=>`<label class="method-option"><input type="checkbox" ${w.methods.includes(n)?'checked':''} onchange="App.attack.toggleMethod('${n}')"><span><strong>${methods[n].label}</strong><small>${n} · ${methods[n].gen?'攻击模型 + Judge':'仅需 Judge'}${methods[n].process?' · 含过程裁判':''}</small></span></label>`).join('')}</div>`).join('')}</details>`:''}<div class="setup-hint section-gap">已选 ${w.scenes.length} 个场景、${w.methods.length} 种方法${!w.methods.length?'请先选择风险场景':req.attacker?'需要攻击模型与 Judge':'当前方法不需要攻击模型，仅需 Judge'}</div>`;
  if(w.step===3){const count=A.banks.get(w.bankId)?.items.length||0;body=`<div class="setup-confirm"><div><span class="muted">被测对象</span><strong>${E(m.name)}</strong></div><div><span class="muted">测试范围</span><strong>${w.scenes.length} 个场景 / ${w.methods.length} 种方法</strong></div></div><div class="setup-confirm"><div><span>演练题库</span><strong>${E(A.banks.get(w.bankId)?.name)}</strong></div><div><span>计划攻击记录</span><strong>${count} 题 × ${w.methods.length} 种方法 = ${count*w.methods.length} 条</strong></div></div>${w.methods.includes('FigStep')?`<label class="setup-checkbox section-gap"><input type="checkbox" ${w.figHelper?'checked':''} onchange="App.attack.wizard.figHelper=this.checked;App.attack.wizardModal()">图片指令启用辅助改写（需要攻击模型）</label>`:''}
   <div class="setup-section"><h3>本次需要的演练模型</h3><p class="hint">选择您已配置的连接；如有默认配置会自动带入</p>${req.attacker?X.wizardRole('attacker','攻击模型 *','用于生成输入、翻译或改写推荐自有 DeepSeek-V3 服务'):'<div class="setup-hint">所选方法通过模板或规则生成输入，无需攻击模型</div>'}${X.wizardRole('judge','评价模型 *','独立评价测试输出推荐 DeepSeek-V4-Flash 推理模式')}
   </div>
   ${w.methods.includes('NanoGCG')?`<section class="setup-section"><h3>白盒攻击配置</h3><div class="field"><label for="whitebox-target">目标输出 *</label><input id="whitebox-target" value="${E(w.targetOutput||'')}" oninput="App.attack.wizard.targetOutput=this.value"></div><div class="field"><label for="whitebox-steps">优化步数 *</label><input id="whitebox-steps" type="number" min="1" step="1" value="${w.optimizationSteps||100}" oninput="App.attack.wizard.optimizationSteps=Number(this.value)"></div><p>本次为模拟演练，未加载真实权重</p></section>`:''}<section class="setup-section"><h3>执行参数</h3><div class="form-grid section-gap"><div class="field"><label for="engine-concurrency">并发测试单元</label><select id="engine-concurrency" onchange="App.attack.wizard.concurrency=Number(this.value)">${[1,2,4,8].map(n=>`<option ${w.concurrency===n?'selected':''}>${n}</option>`).join('')}</select></div>${req.process?`<div class="field"><label for="engine-rounds">迭代方法最大轮数</label><input id="engine-rounds" type="number" min="1" step="1" value="${w.maxRounds}" oninput="App.attack.wizard.maxRounds=Number(this.value)"></div>`:''}</div></section><p class="hint section-gap">运行本地模拟，不调用模型、不消耗 Token平台不提供真实服务或调用额度</p>`;}
  X.presentWizard(head+body+'<p id="wizard-error" class="error-message" role="alert"></p>',`<span class="muted small-text" style="margin-right:auto">${w.step} / 3</span><button class="btn" onclick="${w.step===1?"App.attack.setTab('tasks')":'App.attack.wizard.step--;App.attack.wizardModal()'}">${w.step===1?'取消':'上一步'}</button><button class="btn primary" onclick="App.attack.wizardNext()">${w.step===3?'启动模拟演练':'下一步 →'}</button>`,{wide:true});
 },
 presentWizard(body,footer){X.creationHTML=`<section class="card creation-page"><div class="card-body">${body}</div><div class="creation-footer">${footer}</div></section>`;A.render();},
 wizardRole(role,label,hint){const w=X.wizard,r=role==='process'?'judge':role;return `<div class="field section-gap"><div class="flex between"><label for="task-${role}">${label}</label></div>${C.roleSelect(r,w[role],'task-'+role,`App.attack.wizard.${role}=this.value;App.attack.wizardModal()`)}<p class="hint">${hint}</p>${w[role]===w.model?'<p class="hint red-text">当前与被测对象使用同一连接，建议选择独立模型以减少自评偏差</p>':''}</div>`;},
 toggleScene(id){const w=X.wizard;if(!X.sceneAvailable(X.scene(id),X.model(w.model)))return;if(w.scenes.includes(id)){w.scenes=w.scenes.filter(x=>x!==id);w.methods=w.methods.filter(n=>!X.scene(id).methods.includes(n));}else{w.scenes.push(id);w.methods.push(...X.scene(id).methods);}X.wizardModal();},
 toggleMethod(n){const w=X.wizard;w.methods=w.methods.includes(n)?w.methods.filter(x=>x!==n):[...w.methods,n];w.methodsExpanded=true;X.wizardModal();},
 taskValidation(w){const m=X.model(w.model);if(!w.name.trim())return '请填写演练任务名称';if(!m.id)return '请选择被测模型或智能体';if(!m.sample&&!C.ready(m))return '被测连接缺少 API Key，请在接入配置中补充';if(!A.banks.get(w.bankId))return '请选择演练题库';if(w.step<2)return '';if(!w.scenes.length||!w.methods.length)return '请至少选择一个场景和一种测试方法';if(w.scenes.some(id=>!X.sceneAvailable(X.scene(id),m)))return '存在与被测对象能力不匹配的场景';if(w.scenes.some(id=>!X.scene(id).methods.some(n=>w.methods.includes(n))))return '每个选中的场景至少保留一种方法，或取消该场景';if(w.step<3)return '';if(w.methods.includes('NanoGCG')&&(!w.targetOutput?.trim()||!Number.isSafeInteger(w.optimizationSteps)||w.optimizationSteps<1))return '请填写目标输出与大于 0 的整数优化步数';if(!Number.isSafeInteger(w.maxRounds)||w.maxRounds<1)return '最大轮数请填写大于 0 的整数';const req=X.requirements(w.methods,w.figHelper);for(const role of ['judge',...(req.attacker?['attacker']:[]),...(req.process&&w.processMode==='separate'?['process']:[])]){const r=role==='process'?'judge':role,conn=C.eligible(r).find(x=>x.id===w[role]);if(!conn)return `请先配置并选择${role==='judge'?'最终 Judge':role==='process'?'过程裁判':'攻击模型'}`;if(!C.ready(conn))return `${conn.name} 缺少 API Key，请编辑接入配置重新填写`;}return '';},
 wizardNext(){const w=X.wizard,error=X.taskValidation(w);if(error){const el=document.getElementById('wizard-error');el.textContent=error;el.scrollIntoView?.({block:'nearest'});return;}if(w.step<3){w.step++;X.wizardModal();return;}
  const req=X.requirements(w.methods,w.figHelper),target=X.model(w.model),judge=X.model(w.judge),attacker=req.attacker?X.model(w.attacker):null,process=req.process?X.model(w.processMode==='reuse'?w.judge:w.process):null;
  const snapshot=m=>m?{accessType:m.accessType||'api',...(m.accessType==='weights'?{node:m.node,modelPath:m.modelPath,tokenizerPath:m.tokenizerPath,validationStatus:m.validationStatus}:{}),id:m.id,name:m.name,model:m.model,endpoint:m.sample?'':m.endpoint,protocol:m.protocol,kind:m.kind,caps:[...m.caps],auth:m.auth,header:m.header||'',thinking:!!m.thinking,timeout:m.timeout,...(m.protocol==='http'?{body:m.body,responsePath:m.responsePath,sessionPath:m.sessionPath}:{} )}:null;
  const bindings=w.methods.map(n=>({method:n,registry:X.methodInfo[n][0],generator:methods[n].gen||(n==='FigStep'&&w.figHelper)?{parameter:methods[n].param,connectionId:attacker.id}:null,processJudge:methods[n].process?process.id:null,finalJudge:judge.id}));
  const engine={...(w.methods.includes('NanoGCG')?{whitebox:{targetOutput:w.targetOutput.trim(),steps:w.optimizationSteps,simulated:true}}:{}),attacker:attacker?attacker.name+(attacker.model?' · '+attacker.model:''):'不需要（模板 / 规则生成）',judge:judge.name+(judge.model?' · '+judge.model:''),process:process?process.name+(w.processMode==='reuse'?'（复用 Judge，独立调用）':''):'不需要',concurrency:w.concurrency,maxRounds:req.process?w.maxRounds:1,methods:[...w.methods],figHelper:w.methods.includes('FigStep')&&w.figHelper,roles:{attacker:snapshot(attacker),judge:snapshot(judge),process:snapshot(process)},bindings};
  const t=X.makeTask(w.name.trim(),w.model,w.scenes,'dataset',A.banks.get(w.bankId).items.length,engine);t.bankSnapshot={id:w.bankId,name:A.banks.get(w.bankId).name,items:JSON.parse(JSON.stringify(A.banks.get(w.bankId).items))};t.units.forEach((u,i)=>u.questionId=t.bankSnapshot.items[i%t.bankSnapshot.items.length].id);t.targetSnapshot=snapshot(target);t.units.forEach(u=>u.rounds=methods[u.method].process?w.maxRounds:1);X.db.tasks.unshift(t);A.save();A.closeModal();X.open(t.id);X.detailTab='progress';A.render();A.toast('模拟演练已启动，不产生真实模型调用');
 },
 config(t){return `<div class="card"><div class="card-head"><h3 class="card-title">本次演练配置快照</h3>${A.badge('任务创建时锁定','gray')}</div><div class="card-body"><div class="kv"><span>被测对象</span><strong>${E(X.targetFor(t).name)}</strong></div><div class="kv"><span>攻击模型</span><span>${E(t.engine.attacker)}</span></div><div class="kv"><span>评价模型</span><span>${E(t.engine.judge)}</span></div><div class="kv snapshot-scenes"><span>攻击场景</span><div class="snapshot-scene-list">${t.scenes.map(id=>`<div class="snapshot-scene-row"><span class="snapshot-scene-name">${E(X.scene(id)?.name||id)}：</span><span class="snapshot-scene-methods">${X.taskMethods(t,id).map(n=>E(methods[n]?.label?methods[n].label+'（'+n+'）':n)).join('、')}</span></div>`).join('')}</div></div>${t.engine.whitebox?`<div class="kv"><span>白盒攻击配置</span><span>目标输出：${E(t.engine.whitebox.targetOutput)}<br>优化步数：${t.engine.whitebox.steps}</span></div>`:''}${t.bankSnapshot?`<div class="kv"><span>演练题库</span><span>${E(t.bankSnapshot.name)} · ${t.bankSnapshot.items.length} 题</span></div>`:''}<div class="kv"><span>执行参数</span><span>每种方法 ${t.sampleCount} 个样本 · 最大 ${t.engine.maxRounds} 轮 · 并发 ${t.engine.concurrency}</span></div></div></div>`;}

});
// The process-judge picker still registers a model with the normal Judge capability.
const openConnection=C.open.bind(C);
C.open=function(id,role='target',preset='',returnTo=null){openConnection(id,role==='process'?'judge':role,preset,returnTo);C.role=role;};
})();
