(function(){
'use strict';
const A=window.App,X=A.attack,C=A.connections,E=A.escape;
const builtin={id:'advbench-520',name:'AdvBench 安全基准',source:'OpenRT · AdvBench',builtin:true,items:window.AdvBenchData};
const salad={id:'salad-bench-1000',name:'SALAD-Bench 通用安全题库（英文·1000题子集）',industry:'通用',source:'OpenSafetyLab · SALAD-Bench',builtin:true,items:window.SaladBankData,provenance:window.SaladBankProvenance};
const B=A.banks={pending:null,page:1,
 get db(){return [builtin,salad,...(A.data.banks||[])];},get(id){return B.db.find(b=>b.id===id);},
 render(){return `<div class="setup-page-head"><h2>全部题库</h2><div class="flex"><button class="btn" onclick="App.banks.extractStart()">从攻击记录提取</button><button class="btn" onclick="App.banks.template()">下载 JSON 模板</button><button class="btn primary" onclick="App.banks.importDialog()">导入题库</button></div></div><div class="card"><div class="table-wrap"><table><thead><tr><th>题库名称</th><th>题目数量</th><th>来源</th><th>操作</th></tr></thead><tbody>${B.db.map(b=>`<tr><td><strong>${E(b.name)}</strong></td><td>${b.items.length}</td><td>${b.builtin?'内置 · OpenRT':E(b.source||'用户导入')}</td><td><button class="link-btn" onclick="App.banks.open('${b.id}')">查看题目</button><button class="link-btn" style="margin-left:16px" onclick="App.banks.export('${b.id}')">导出 JSON</button></td></tr>`).join('')}</tbody></table></div></div>`;},
 open(id,page=1){const b=B.get(id);if(!b)return;const pages=Math.ceil(b.items.length/20);page=Math.min(Math.max(1,page),pages);A.drawer(b.name,`<div class="table-wrap"><table><thead><tr><th>题目 ID</th><th>测试问题</th></tr></thead><tbody>${b.items.slice((page-1)*20,page*20).map(q=>`<tr><td>${E(q.id)}</td><td style="white-space:normal;min-width:280px">${E(q.prompt)}</td></tr>`).join('')}</tbody></table></div>`,`<span>${b.items.length} 题 · ${page} / ${pages}</span><button class="btn" ${page===1?'disabled':''} onclick="App.banks.open('${id}',${page-1})">上一页</button><button class="btn" ${page===pages?'disabled':''} onclick="App.banks.open('${id}',${page+1})">下一页</button>`);},
 template(){A.download('题库导入模板.json',JSON.stringify({schemaVersion:1,name:'自定义安全题库',items:[{id:'Q-001',prompt:'请解释如何保护个人隐私',category:'隐私保护'},{id:'Q-002',prompt:'说明遇到可疑链接时应如何处理',category:'网络安全'}]},null,2),'application/json');},
 export(id){const b=B.get(id);A.download(b.name+'.json',JSON.stringify({schemaVersion:1,name:b.name,...(b.provenance?{provenance:b.provenance}:{}),items:b.items},null,2),'application/json');},
 parse(text,fileName){let parsed;const clean=text.replace(/^\uFEFF/,'');if(fileName.toLowerCase().endsWith('.jsonl')){parsed=clean.split(/\r?\n/).map((line,i)=>{if(!line.trim())return null;try{return JSON.parse(line);}catch(e){throw Error(`第 ${i+1} 行不是有效 JSON`);}}).filter(v=>v!==null);}else{try{parsed=JSON.parse(clean);}catch(e){throw Error('JSON 文件格式错误，请检查逗号、引号及括号');}}
 const rows=Array.isArray(parsed)?parsed:parsed?.items;if(!Array.isArray(rows))throw Error('文件应为题目数组，或包含 items 数组的对象');if(!rows.length)throw Error('题库不能为空');if(rows.length>10000)throw Error('单次最多导入 10000 题');
 const ids=new Set(),prompts=new Set(),errors=[],items=[];let duplicates=0;
 rows.forEach((row,i)=>{const at=`第 ${i+1} 题`;if(!row||typeof row!=='object'||Array.isArray(row)){errors.push(at+'需为对象');return;}if(['image','image_path','messages','context'].some(k=>row[k]!=null)){errors.push(at+'含当前文本题库不支持的图片、会话或上下文字段');return;}
 const fields=['prompt','question','goal','jailbreak_prompt','input'].filter(k=>row[k]!=null);if(!fields.length||fields.some(k=>typeof row[k]!=='string'||!row[k].trim())){errors.push(at+'缺少非空文本 prompt（也支持 question / goal / jailbreak_prompt / input）');return;}
 const prompt=row[fields[0]].trim();if(fields.some(k=>row[k].trim()!==prompt)){errors.push(at+'的多个问题字段内容不一致');return;}if(prompt.length>20000){errors.push(at+'的问题超过 20000 字符');return;}
 const id=row.id==null?'Q-'+String(i+1).padStart(5,'0'):String(row.id).trim();if(!['string','number','undefined'].includes(typeof row.id)||!id||id.length>120||ids.has(id)){errors.push(at+'的 ID 为空、无效或重复');return;}ids.add(id);
 if(row.category!=null&&(typeof row.category!=='string'||row.category.length>200)){errors.push(at+'的 category 必须是 200 字符以内文本');return;}
 const target=row.target??row.answer;if(target!=null&&(typeof target!=='string'||target.length>20000)){errors.push(at+'的参考目标必须是 20000 字符以内文本');return;}
 if(prompts.has(prompt))duplicates++;prompts.add(prompt);items.push({id,prompt,...(row.category?{category:row.category.trim()}:{}),...(target?{target}:{})});});
 if(errors.length)throw Error(errors.slice(0,8).join('\n')+(errors.length>8?`\n另有 ${errors.length-8} 项错误`:''));const name=typeof parsed.name==='string'&&parsed.name.trim()?parsed.name.trim().slice(0,100):fileName.replace(/\.(json|jsonl)$/i,'');return {name,items,duplicates};
 },
 importDialog(){B.pending=null;A.modal('导入题库',`<div class="field"><label for="bank-file">JSON / JSONL 文件</label><input id="bank-file" type="file" accept=".json,.jsonl,application/json" onchange="App.banks.read(this.files[0])"></div><p>必填：测试问题 prompt</p><p>可选：id、category、target</p><p>兼容 question、goal、jailbreak_prompt、input；单文件不超过 5 MB</p><div id="bank-import-status" role="status" style="white-space:pre-wrap;margin:16px 0"></div><div class="field"><label for="bank-name">题库名称</label><input id="bank-name" maxlength="100"></div>`,`<button class="btn" onclick="App.closeModal()">取消</button><button id="bank-import-confirm" class="btn primary" disabled onclick="App.banks.confirm()">确认导入</button>`);},
 async read(file){const ticket=B.readTicket=(B.readTicket||0)+1;B.pending=null;const button=document.getElementById('bank-import-confirm'),status=document.getElementById('bank-import-status');button.disabled=true;if(!file)return;try{if(file.size>5*1024*1024)throw Error('文件超过 5 MB');if(!/\.(json|jsonl)$/i.test(file.name))throw Error('请选择 JSON 或 JSONL 文件');const result=B.parse(await file.text(),file.name);if(ticket!==B.readTicket||!document.getElementById('bank-import-status'))return;B.pending=result;document.getElementById('bank-name').value=result.name;status.textContent=`校验通过 · ${result.items.length} 题`+(result.duplicates?`\n发现 ${result.duplicates} 条重复问题，将按不同 ID 保留`:'');button.disabled=false;}catch(e){if(ticket===B.readTicket)status.textContent=e.message;}},
 confirm(){if(!B.pending)return;const name=document.getElementById('bank-name').value.trim();if(!name){document.getElementById('bank-import-status').textContent='请填写题库名称';return;}const bank={id:'bank-'+Date.now()+'-'+Math.random().toString(36).slice(2,7),name,items:B.pending.items};A.data.banks ||= [];A.data.banks.push(bank);try{localStorage.setItem('zhian-standalone-attack',JSON.stringify(A.data));}catch(e){A.data.banks.pop();document.getElementById('bank-import-status').textContent='浏览器存储空间不足，请减小题库后重试';return;}B.pending=null;A.closeModal();X.setTab('banks');A.toast('题库已导入');}
};
const init=A.modules.attack.init;A.modules.attack.init=function(){init();A.data.banks ||= [];if(!X.db.simpleConnectionsVersion){for(const m of C.db){if(m.id==='m1'){m.name=m.model='Qwen2.5-72B-Instruct';m.vendor='Qwen';}if(m.id==='m2'){m.name='InternLM3-8B-Instruct Agent';m.model='InternLM3-8B-Instruct';}if(m.id==='m3'){m.name=m.model='Qwen2.5-VL-72B';}m.sample=false;m.demoConfigured=true;}for(const [id,name] of [['deepseek-v3','DeepSeek-V3'],['deepseek-judge','DeepSeek-V4 Pro']])if(!C.db.some(m=>m.id===id))C.db.push({id,name,model:name,vendor:'DeepSeek',endpoint:'https://api.deepseek.com',kind:'model',schema:2,sample:false,demoConfigured:true,auth:'none',protocol:'openai',hosting:'cloud',caps:['text','chat'],uses:['target','attacker','judge'],timeout:60});X.db.simpleConnectionsVersion=1;}if(!X.db.threeModelPresetsVersion){
 const removed=X.db.models.filter(m=>['m2','m3'].includes(m.id));X.db.retiredPresetModels=[...(X.db.retiredPresetModels||[]),...removed];X.db.models=X.db.models.filter(m=>!['m2','m3'].includes(m.id));
 const flash=X.db.models.find(m=>m.id==='deepseek-judge');if(flash){flash.name='DeepSeek-V4-Flash';flash.model='deepseek-v4-flash';}
 X.db.threeModelPresetsVersion=1;
}
X.db.defaults={attacker:'deepseek-v3',judge:'deepseek-judge',processMode:'reuse',process:''};};
const content=X.sampleContent;X.sampleContent=function(u,t=X.task){const c=content(u),q=t?.bankSnapshot?.items.find(q=>q.id===u.questionId);return q?{...c,prompt:q.prompt}:c;};
})();
